### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by kirkins** [EinAeffchen/Telegram_Crawler#1]
When I run `python3 Connector.py -m 1 -t 900 -r 50 -l 1` I get back:

```
     ->[*] Loading group blacklist...
Traceback (most recent call last):
  File "Connector.py", line 307, in <module>
    main()
  File "Connector.py", line 295, in main
    top = TelegramOperator() #Object is recreated every time to reset the data
  File "Connector.py", line 50, in __init__
    self.initialize_run()
  File "Connector.py", line 210, in initialize_run
    for dialog in dialogs:
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'DialogMethods.get_dialogs' was never awaited
```

**Comment by EinAeffchen** [comment]
Hi, sorry but this is an old project, where I forgot to put down the version numbers. The telegram library used got quite a lot of changes since then and I didn't have the time to maintain this anymore. If you want to make this run as is, try getting a version from around february ( 1.5.x).
